In [1]:
from google.colab import drive
drive.mount('/content/drive') #連雲端硬碟

import pandas as pd
googlepath='/content/drive/MyDrive/巨資雲端技術/' #路徑到指定資料夾

Mounted at /content/drive

In [9]:
df = pd.read_csv(googlepath + "初始資料.csv") #讀取檔案
df = df.drop("週期",axis=1) #刪除週期欄位
df = df.drop("波向",axis=1) #刪除波向欄位
df = df.drop("風向",axis=1) #刪除風向欄位
df #顯示資料框內容

          年   月   日   時    波高    風速
0      2024   1   1   0  3.09  14.9
1      2024   1   1   1  3.31  15.0
2      2024   1   1   2  3.38  14.8
3      2024   1   1   3  3.29  14.7
4      2024   1   1   4  3.86  15.6
...     ...  ..  ..  ..   ...   ...
17539  2025  12  31  19 -9.90  -9.9
17540  2025  12  31  20 -9.90  -9.9
17541  2025  12  31  21 -9.90  -9.9
17542  2025  12  31  22 -9.90  -9.9
17543  2025  12  31  23 -9.90  -9.9

[17544 rows x 6 columns]

In [12]:
import numpy as np
'''在資料分析（特別是氣象、水文、醫療或舊型資料庫）中，
常常會用特定的數值（如-9.9、-999或-99）來代表「缺失值」或「異常值」。'''
df.replace(-9.9, np.nan, inplace=True) #將所有的 -9.9 替換為標準的 NaN
df = df.dropna() #刪除有缺失值的整列
df

          年   月   日   時    波高    風速
0      2024   1   1   0  3.09  14.9
1      2024   1   1   1  3.31  15.0
2      2024   1   1   2  3.38  14.8
3      2024   1   1   3  3.29  14.7
4      2024   1   1   4  3.86  15.6
...     ...  ..  ..  ..   ...   ...
17438  2025  12  27  14  1.88  12.2
17462  2025  12  28  14  2.44  12.5
17474  2025  12  29   2  2.00   9.8
17498  2025  12  30   2  1.71   8.0
17522  2025  12  31   2  2.41  13.3

[13388 rows x 6 columns]

In [32]:
df_1 = df[df['月'] == 1] #只保留「月」欄位等於 1 的整列資料
df_1.to_csv(googlepath + "1月.csv", index=False, encoding="utf-8-sig") #結合路徑並輸出CSV檔
df_1

         年  月   日   時    波高    風速
0     2024  1   1   0  3.09  14.9
1     2024  1   1   1  3.31  15.0
2     2024  1   1   2  3.38  14.8
3     2024  1   1   3  3.29  14.7
4     2024  1   1   4  3.86  15.6
...    ... ..  ..  ..   ...   ...
9523  2025  1  31  19  0.64   3.7
9524  2025  1  31  20  0.67   5.4
9525  2025  1  31  21  0.79   4.6
9526  2025  1  31  22  0.79   3.1
9527  2025  1  31  23  0.78   2.4

[1389 rows x 6 columns]

In [34]:
df_2 = df[df['月'] == 2]
df_2.to_csv(googlepath + "2月.csv", index=False, encoding="utf-8-sig")
df_2

          年  月   日   時    波高   風速
744    2024  2   1   0  0.55  2.6
745    2024  2   1   1  0.55  1.4
747    2024  2   1   3  0.49  1.7
748    2024  2   1   4  0.48  1.9
751    2024  2   1   7  0.43  1.5
...     ... ..  ..  ..   ...  ...
10193  2025  2  28  17  0.33  3.4
10194  2025  2  28  18  0.31  3.3
10195  2025  2  28  19  0.31  3.3
10196  2025  2  28  20  0.31  2.2
10197  2025  2  28  21  0.33  1.6

[1310 rows x 6 columns]

In [35]:
df_3 = df[df['月'] == 3]
df_3.to_csv(googlepath + "3月.csv", index=False, encoding="utf-8-sig")
df_3

          年  月   日   時    波高    風速
1440   2024  3   1   0  1.43   8.5
1441   2024  3   1   1  1.72  12.2
1442   2024  3   1   2  2.84  15.0
1443   2024  3   1   3  3.52  15.8
1444   2024  3   1   4  3.13  17.2
...     ... ..  ..  ..   ...   ...
10939  2025  3  31  19  2.54  16.0
10940  2025  3  31  20  2.65  15.8
10941  2025  3  31  21  2.66  15.9
10942  2025  3  31  22  3.37  15.8
10943  2025  3  31  23  3.15  15.1

[1374 rows x 6 columns]

In [36]:
df_4 = df[df['月'] == 4]
df_4.to_csv(googlepath + "4月.csv", index=False, encoding="utf-8-sig")
df_4

          年  月   日   時    波高   風速
2184   2024  4   1   0  0.57  3.0
2185   2024  4   1   1  0.45  2.4
2186   2024  4   1   2  0.38  2.1
2187   2024  4   1   3  0.34  1.1
2190   2024  4   1   6  0.31  3.5
...     ... ..  ..  ..   ...  ...
11659  2025  4  30  19  0.62  2.9
11660  2025  4  30  20  0.54  1.7
11661  2025  4  30  21  0.52  2.0
11662  2025  4  30  22  0.54  3.6
11663  2025  4  30  23  0.47  4.1

[920 rows x 6 columns]

In [37]:
df_5 = df[df['月'] == 5]
df_5.to_csv(googlepath + "5月.csv", index=False, encoding="utf-8-sig")
df_5

          年  月   日   時    波高    風速
2904   2024  5   1   0  0.32   7.8
2908   2024  5   1   4  0.46  10.4
2912   2024  5   1   8  0.35   6.1
2916   2024  5   1  12  0.49   6.2
2920   2024  5   1  16  1.43   3.4
...     ... ..  ..  ..   ...   ...
12390  2025  5  31   6  0.83   2.5
12396  2025  5  31  12  0.81   2.9
12400  2025  5  31  16  0.84   4.9
12402  2025  5  31  18  0.79   4.6
12406  2025  5  31  22  0.74   2.2

[1093 rows x 6 columns]

In [38]:
df_6 = df[df['月'] == 6]
df_6.to_csv(googlepath + "6月.csv", index=False, encoding="utf-8-sig")
df_6

          年  月   日   時    波高   風速
3648   2024  6   1   0  0.48  5.3
3652   2024  6   1   4  0.53  3.8
3656   2024  6   1   8  0.50  2.6
3660   2024  6   1  12  0.51  4.5
3664   2024  6   1  16  0.82  2.7
...     ... ..  ..  ..   ...  ...
13122  2025  6  30  18  0.31  3.1
13123  2025  6  30  19  0.32  2.2
13124  2025  6  30  20  0.28  1.4
13125  2025  6  30  21  0.33  1.1
13127  2025  6  30  23  0.31  2.7

[1183 rows x 6 columns]

In [39]:
df_7 = df[df['月'] == 7]
df_7.to_csv(googlepath + "7月.csv", index=False, encoding="utf-8-sig")
df_7

          年  月   日   時    波高   風速
4368   2024  7   1   0  0.57  7.7
4369   2024  7   1   1  0.60  6.8
4370   2024  7   1   2  0.59  6.6
4371   2024  7   1   3  0.62  6.4
4372   2024  7   1   4  0.67  6.7
...     ... ..  ..  ..   ...  ...
13866  2025  7  31  18  0.73  9.5
13867  2025  7  31  19  0.67  6.5
13868  2025  7  31  20  0.62  5.6
13869  2025  7  31  21  0.66  7.2
13870  2025  7  31  22  0.78  7.4

[1356 rows x 6 columns]

In [40]:
df_8 = df[df['月'] == 8]
df_8.to_csv(googlepath + "8月.csv", index=False, encoding="utf-8-sig")
df_8

          年  月   日   時    波高   風速
5112   2024  8   1   0  0.62  4.8
5113   2024  8   1   1  0.56  5.4
5114   2024  8   1   2  0.55  5.2
5115   2024  8   1   3  0.55  5.1
5116   2024  8   1   4  0.61  5.7
...     ... ..  ..  ..   ...  ...
14604  2025  8  31  12  0.38  2.8
14608  2025  8  31  16  0.37  3.4
14609  2025  8  31  17  0.35  1.8
14611  2025  8  31  19  0.33  1.1
14615  2025  8  31  23  0.27  1.6

[1309 rows x 6 columns]

In [41]:
df_9 = df[df['月'] == 9]
df_9.to_csv(googlepath + "9月.csv", index=False, encoding="utf-8-sig")
df_9

          年  月   日   時    波高   風速
5856   2024  9   1   0  0.54  1.6
5857   2024  9   1   1  0.57  2.4
5858   2024  9   1   2  0.54  2.1
5859   2024  9   1   3  0.57  2.0
5860   2024  9   1   4  0.48  2.9
...     ... ..  ..  ..   ...  ...
15329  2025  9  30  17  0.46  3.7
15330  2025  9  30  18  0.37  3.1
15332  2025  9  30  20  0.39  2.5
15333  2025  9  30  21  0.33  2.5
15334  2025  9  30  22  0.33  1.7

[1162 rows x 6 columns]

In [42]:
df_10 = df[df['月'] == 10]
df_10.to_csv(googlepath + "10月.csv", index=False, encoding="utf-8-sig")
df_10

          年   月   日   時    波高    風速
6576   2024  10   1   0  2.39   2.2
6577   2024  10   1   1  2.04   4.4
6578   2024  10   1   2  1.86   2.2
6580   2024  10   1   4  1.65   3.0
6581   2024  10   1   5  2.01   2.6
...     ...  ..  ..  ..   ...   ...
16071  2025  10  31  15  2.27  12.8
16072  2025  10  31  16  2.30  12.8
16075  2025  10  31  19  1.99  12.5
16077  2025  10  31  21  2.33  12.5
16078  2025  10  31  22  2.34  12.5

[1161 rows x 6 columns]

In [43]:
df_11 = df[df['月'] == 11]
df_11.to_csv(googlepath + "11月.csv", index=False, encoding="utf-8-sig")
df_11

          年   月   日   時    波高    風速
7320   2024  11   1   0  1.91  16.5
7321   2024  11   1   1  2.26  17.4
7322   2024  11   1   2  2.26  18.5
7323   2024  11   1   3  2.04  15.7
7324   2024  11   1   4  2.23  16.5
...     ...  ..  ..  ..   ...   ...
16794  2025  11  30  18  0.98   5.3
16796  2025  11  30  20  0.77   4.0
16797  2025  11  30  21  0.72   3.0
16798  2025  11  30  22  0.65   4.2
16799  2025  11  30  23  0.58   3.6

[722 rows x 6 columns]

In [44]:
df_12 = df[df['月'] == 12]
df_12.to_csv(googlepath + "12月.csv", index=False, encoding="utf-8-sig")
df_12

          年   月   日   時    波高    風速
8040   2024  12   1   0  0.85   3.2
8044   2024  12   1   4  0.53   3.0
8050   2024  12   1  10  0.85   2.5
8051   2024  12   1  11  0.95   4.3
8052   2024  12   1  12  0.93   3.8
...     ...  ..  ..  ..   ...   ...
17438  2025  12  27  14  1.88  12.2
17462  2025  12  28  14  2.44  12.5
17474  2025  12  29   2  2.00   9.8
17498  2025  12  30   2  1.71   8.0
17522  2025  12  31   2  2.41  13.3

[409 rows x 6 columns]